### PR TITLE
Zen 14174

### PR DESCRIPTION
**Pull request by dougsyer**
I needed to get the queue monitoring up for invalidations, etc on our zenoss system, so i added this fix which allows us to poll the invalidations, collector calls for remote hub queues.

### CODE REVIEW

**Comment by csmouse** [comment]
PR has aged out. Closing.

**Comment by dougsyer** [comment]
Seriously i spent the time to allow us to monitor non volatile zenoss queues and share it

**Comment by csmouse** [comment]
Hi @dougsyer - while we appreciate the effort you put into this, our licensing prohibits us from accepting commits from 3rd parties.

**Comment by jregovic** [comment]
What license prevents accepting commits? Why even make the repo available then?

**Comment by dougsyer** [comment]
This one was to fix it so you can model invalidation and collector call queues in zenoss since they have non url safe characters in them.  I dont really care that the pull request is closed as much as i care that thr bug is still there

**Pull request closed without merging**
